### ISSUE TITLE
Issues with modules

### ISSUE THREAD

**Issue by acseros** [OCA/l10n-romania#102]
Hello,

I installed the Romania - Localization Config module. But I have the following issues the first on the settings page the checkboxes are not remain saved and the second issue is in the General Settings --> Business Documents --> Documents Layout
when I change the layout to l10n_ro_report_invoice_document and press Preview Document I got the following error message.
Thank you in advance!

Best regards,
Arpad Cseros

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_1093
  File "<template>", line 2, in body_call_content_1091
  File "<template>", line 4, in set_1044
AttributeError: 'res.company' object has no attribute 'partner_shipping_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 2025, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1963, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_actions_report.py", line 734, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_actions_report.py", line 774, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_actions_report.py", line 548, in render_template
    return view_obj.render_template(template, values)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 1177, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo13/odoo/addons/website/models/ir_ui_view.py", line 336, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo13/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise e
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_preview_externalreport_1018
  File "<template>", line 3, in body_call_content_1016
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise e
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_external_layout_1029
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'res.company' object has no attribute 'partner_shipping_id'
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_1093
  File "<template>", line 2, in body_call_content_1091
  File "<template>", line 4, in set_1044
AttributeError: 'res.company' object has no attribute 'partner_shipping_id'

Error to render compiling AST
AttributeError: 'res.company' object has no attribute 'partner_shipping_id'
Template: account.report_invoice_document
Path: /t/t/t[2]/t
Node: <t t-if="o.partner_shipping_id and (o.partner_shipping_id != o.partner_id)">
                <t t-set="information_block">
                    <div groups="sale.group_delivery_invoice_address">
                        <strong>Shipping Address:</strong>
                        <div t-field="o.partner_shipping_id" t-options="{&quot;widget&quot;: &quot;contact&quot;, &quot;fields&quot;: [&quot;address&quot;, &quot;name&quot;], &quot;no_marker&quot;: True}"/>
                    </div>
                </t>
            </t>

**Comment by acseros** [comment]
duplicate
