### ISSUE TITLE
Problema la trimiterea mailurilor

### ISSUE THREAD

**Issue by FreezeS** [OCA/l10n-romania#369]
Salut,

Am gasit o problema cand incerc sa trimit mailuri pe V15.

Instalare proaspata, cu sale_management si l10n_ro_config.
Ultimul commit pe odoo: a7299baf986b48aa83c60d92b6106e6f89fb9156, 
ultimul pe l10n-romania: 53756f9790f30060d907a80b48f45c37c56ec0f3

In Settings - Romania am bifat tot mai putin Romanian DVI si Romanian Stock Picking Comment Template.
Am setat Outgoing si Incoming mail servers.

La Sales am facut primii 3 pasi din wizard iar cand dau Send sample quotation primesc eroarea de mai jos:

`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_627>", line 44, in template_627
KeyError: 'o'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo15/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo15/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo15/odoo/addons/sale/models/res_company.py", line 107, in action_open_sale_onboarding_sample_quotation
    update_values = message_composer._onchange_template_id(template.id, 'comment', 'sale.order', sample_sales_order.id)['value']
  File "/opt/odoo15/odoo/addons/mail/wizard/mail_compose_message.py", line 552, in _onchange_template_id
    values = self.generate_email_for_composer(
  File "/opt/odoo15/odoo/addons/mail/wizard/mail_compose_message.py", line 663, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields)
  File "/opt/odoo15/odoo/addons/account_edi/models/mail_template.py", line 21, in generate_email
    res = super().generate_email(res_ids, fields)
  File "/opt/odoo15/odoo/addons/mail/models/mail_template.py", line 236, in generate_email
    result, format = report._render_qweb_pdf([res_id])
  File "/opt/odoo15/odoo/addons/account/models/ir_actions_report.py", line 49, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_actions_report.py", line 897, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_actions_report.py", line 941, in _render_qweb_html
    return self._render_template(self.report_name, data), 'html'
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_actions_report.py", line 677, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 1985, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/opt/odoo15/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 1993, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/opt/odoo15/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 221, in render_template
    raise e
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1070>", line 52, in template_1070
  File "<template_1070>", line 48, in t_call_content
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 221, in render_template
    raise e
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1069>", line 974, in template_1069
  File "<template_1069>", line 734, in t_call_content
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: 'o'
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_627>", line 44, in template_627
KeyError: 'o'

Error when render the template
KeyError: 'o'
Template: account.document_tax_totals
Path: /t/t/tr/t
Node: <t t-if="o.is_l10n_ro_record"/>                    
`

Mai e ceva ce am uitat sa setez?

**Comment by feketemihai** [comment]
@mcojocaru Verifici tu raportul de factura pe 15 in tax_totals, te rog.

**Comment by feketemihai** [comment]
@FreezeS S-au facut modificarile, mai ai problema sau putem inchide issue?

**Comment by FreezeS** [comment]
@feketemihai am verificat, merge acuma, se poate inchide.
