### ISSUE TITLE
After installing l10n_ro_stock - V13

### ISSUE THREAD

**Issue by neoziv** [OCA/l10n-romania#68]
Eroare:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 664, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/odoo/odoo-server/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: Elementul '<field name="name">' nu poate fi localizat în vizualizarea părinte 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 148, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/odoo/odoo-server/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Elementul '<field name="name">' nu poate fi localizat în vizualizarea părinte 

Eroare context:
Vizualizare`stock.location.merchandise_type.search`
[view_id: 1448, xml_id: indisp., model: stock.location, parent_id: 654]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo-server/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 148, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/odoo/odoo-server/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
odoo.tools.convert.ParseError: "Elementul '<field name="name">' nu poate fi localizat în vizualizarea părinte 

Eroare context:
Vizualizare`stock.location.merchandise_type.search`
[view_id: 1448, xml_id: indisp., model: stock.location, parent_id: 654]" while parsing /odoo/custom/addons/l10n-romania/l10n_ro_stock/views/stock_location_view.xml:2, near
<odoo>
    <record id="view_location_form" model="ir.ui.view">
        <field name="name">stock.location.merchandise_type</field>
        <field name="model">stock.location</field>
        <field name="inherit_id" ref="stock.view_location_form"/>
        <field name="arch" type="xml">
            <field name="usage" position="after">
                <field name="merchandise_type"/>
            </field>
        </field>
    </record>
    <record id="view_location_search" model="ir.ui.view">
        <field name="name">stock.location.merchandise_type.search</field>
        <field name="model">stock.location</field>
        <field name="inherit_id" ref="stock.view_location_search"/>
        <field name="arch" type="xml">
            <field name="name" position="after">
                <field name="merchandise_type"/>
            </field>
        </field>
    </record>
    <record id="view_location_tree2" model="ir.ui.view">
        <field name="name">stock.location.merchandise_type.tree</field>
        <field name="model">stock.location</field>
        <field name="inherit_id" ref="stock.view_location_tree2"/>
        <field name="arch" type="xml">
            <field name="usage" position="after">
                <field name="merchandise_type"/>
            </field>
        </field>
    </record>
</odoo>

**Comment by feketemihai** [comment]
@neoziv I know, there was a change in Odoo main view, changing the field from name to complete_name, i already included the fix in #66 . It will be available after the merge of the PR.
